import type Anthropic from '@anthropic-ai/sdk'

import type { AgentEvent, EmitFn } from '@/lib/agent/events'
import { buildOpeningMessage, buildSystem } from '@/lib/agent/prompt'
import { TOOLS, executeClientTool, isClientTool } from '@/lib/agent/tools'
import { EFFORT, MAX_TOKENS, MODEL, THINKING, callClaude } from '@/lib/anthropic/call'
import { openSubtaskTitles } from '@/lib/store'
import type { Task } from '@/lib/types'

/**
 * Runaway backstop only — not a budget, and not tuned to be reached. A budget
 * belongs outside this function, where the agent cannot see it. Set high enough
 * that a real run always ends because the model is finished, never because the
 * loop ran out of permission.
 */
const MAX_TURNS = 200

export interface RunOptions {
  onEvent: EmitFn
  /** Owned by the caller. The loop forwards it and never creates or clears one. */
  signal?: AbortSignal
}

export interface RunResult {
  runId: string
  turns: number
  stopReason: string | null
}

/**
 * runAgentLoop() — the agent loop.
 *
 * Note what this function does not take: a budget, a cost ceiling, a spend
 * allowance. It has no tool for checking one and no parameter for raising one.
 * Whatever governs how much a run is allowed to cost lives outside this
 * function, in the caller — which means the agent cannot skip it, call it
 * early, or talk its way past it. That placement is the whole idea.
 */
export async function runAgentLoop(task: Task, { onEvent, signal }: RunOptions): Promise<RunResult> {
  const runId = `run-${Date.now().toString(36)}`
  onEvent({ type: 'run_started', runId, taskId: task.id })

  const messages: Anthropic.MessageParam[] = [
    { role: 'user', content: buildOpeningMessage(task) },
  ]

  let turns = 0
  let stopReason: string | null = null

  /**
   * The _20260209 web tools do their dynamic filtering by running code in a
   * container, so a searching turn comes back with code-execution blocks in it.
   * Every later request then has to name that container or the API rejects it:
   * "container_id is required when there are pending tool uses generated by
   * code execution with tools."
   */
  let containerId: string | null = null

  while (turns < MAX_TURNS) {
    turns += 1
    onEvent({ type: 'turn_started', turn: turns })

    const message = await callClaude(
      {
        model: MODEL,
        max_tokens: MAX_TOKENS,
        thinking: THINKING,
        output_config: { effort: EFFORT },
        system: buildSystem(task, runId, await openSubtaskTitles(task.id)),
        tools: TOOLS,
        messages,
        ...(containerId ? { container: containerId } : {}),
      },
      {
        taskId: task.id,
        runId,
        onText: (text) => onEvent({ type: 'text_delta', text }),
        onThinking: (text) => onEvent({ type: 'thinking_delta', text }),
        signal,
      },
    )

    stopReason = message.stop_reason
    containerId = message.container?.id ?? containerId
    emitServerToolUse(message.content, onEvent)

    // Echoed back verbatim — thinking blocks must survive unedited.
    messages.push({ role: 'assistant', content: message.content })

    // A server-tool turn hit the server-side iteration cap. Re-send to continue.
    if (message.stop_reason === 'pause_turn') continue

    if (message.stop_reason !== 'tool_use') break

    const toolUses = message.content.filter(
      (block): block is Anthropic.ToolUseBlock =>
        block.type === 'tool_use' && isClientTool(block.name),
    )

    /**
     * stop_reason was tool_use, but none of OUR tools are pending. This is a
     * searching turn: the _20260209 web tools run their dynamic filtering
     * inside a code-execution container, and while that container still has
     * work outstanding the turn comes back as tool_use carrying only
     * server_tool_use blocks. It is resumed by re-sending with the container
     * id — the same treatment pause_turn gets — not by ending the run.
     *
     * Getting this wrong ends a run mid-thought and reports it as finished.
     */
    if (toolUses.length === 0) {
      if (message.content.some((block) => block.type === 'server_tool_use')) continue

      // Genuinely nothing to answer with, and an empty user turn is a 400.
      break
    }

    const toolResults: Anthropic.ToolResultBlockParam[] = []

    for (const toolUse of toolUses) {
      onEvent({ type: 'tool_use', name: toolUse.name, label: labelFor(toolUse) })
      try {
        const result = await executeClientTool(toolUse.name, toolUse.input, onEvent)
        toolResults.push({ type: 'tool_result', tool_use_id: toolUse.id, content: result })
      } catch (error) {
        toolResults.push({
          type: 'tool_result',
          tool_use_id: toolUse.id,
          content: error instanceof Error ? error.message : String(error),
          is_error: true,
        })
      }
    }

    // Every result goes back in one user message.
    messages.push({ role: 'user', content: toolResults })
  }

  return { runId, turns, stopReason }
}

/** Surface the server-side searches and fetches so the feed can show them. */
function emitServerToolUse(content: Anthropic.ContentBlock[], onEvent: EmitFn): void {
  for (const block of content) {
    if (block.type !== 'server_tool_use') continue
    const input = block.input as { query?: string; url?: string }

    if (block.name === 'web_search' && input.query) {
      onEvent({ type: 'web_search', query: input.query })
    } else if (block.name === 'web_fetch' && input.url) {
      onEvent({ type: 'web_fetch', url: input.url })
    }
  }
}

function labelFor(toolUse: Anthropic.ToolUseBlock): string {
  const input = toolUse.input as {
    subtasks?: { title: string }[]
    status?: string
    body?: string
  }

  switch (toolUse.name) {
    case 'create_subtasks':
      return `${input.subtasks?.length ?? 0} subtasks`
    case 'update_task':
      return input.status ?? 'fields'
    case 'add_comment':
      return input.body?.slice(0, 60) ?? ''
    case 'attach_report':
      return 'report'
    default:
      return ''
  }
}

export type { AgentEvent }
